### ISSUE TITLE
no way to create internatiolization with Next.js 14

### ISSUE THREAD

**Issue by nicitaacom** [i18next/next-i18next#2254] opened 2024-01-28 07:15 UTC
Mentioned here - https://github.com/i18next/next-i18next/discussions/2223

**Comment by adrai** [comment] 2024-01-28 07:55
Proof it works: https://github.com/i18next/next-i18next/discussions/2223#discussioncomment-7349759

**Comment by adrai** [comment] 2024-01-28 07:56
didn't you read this? https://github.com/i18next/next-i18next/discussions/2223#discussioncomment-7349763

**Comment by nicitaacom** [comment] 2024-01-28 08:46
> didn't you read this? [#2223 (comment)](https://github.com/i18next/next-i18next/discussions/2223#discussioncomment-7349763)

I read this and I replied to this

As you see I got error
And it error not with my project - I got it after `git cline` your example

**Comment by nicitaacom** [comment] 2024-01-28 08:49
Also I read this
![image](https://github.com/i18next/next-i18next/assets/39565703/ba093336-25e2-47b2-bfdb-5d5eb1d645aa)


And see this

![image](https://github.com/i18next/next-i18next/assets/39565703/15421fdc-4b3d-4dc4-abee-b69e7afaef24)

**Comment by nicitaacom** [comment] 2024-01-28 08:55
Also I see this

![image](https://github.com/i18next/next-i18next/assets/39565703/7212aa2c-4239-417e-bdb2-50876456d3b8)


And read this

![image](https://github.com/i18next/next-i18next/assets/39565703/97808115-3af5-45ac-bcbc-8ce07b7d147b)


So what do you say about docs for TypeScript user and about testing your own docs how it works?
I mean docs requires improvement
Library requires fix for this error I send above

**Comment by adrai** [comment] 2024-01-28 09:05
You're mixing stuff here....
In your screenshots I see you're following the example for the Next.js [App router](https://nextjs.org/docs/app) approach... that's not next-i18next...
next-i18next uses the [pages approach](https://nextjs.org/docs/pages) of Next.js
https://stackoverflow.com/questions/76570208/what-is-different-between-app-router-and-pages-router-in-next-js

For next-i18next check this example: https://github.com/i18next/next-i18next/tree/master/examples/simple it is tested on each commit... there are no errors...
I just also tried to clone everything on a new machine... and all works as expected... so I assume your local setup has some issues...
Just to be sure I uploaded a zip file of the simple example, so you have it also here. 
[simple.zip](https://github.com/i18next/next-i18next/files/14075457/simple.zip)

An example for the app router approach is here: https://github.com/i18next/next-app-dir-i18next-example-ts

**Comment by adrai** [comment] 2024-01-28 09:22
Since this is proofed by a lot of users around the world and it works. I'll close this issue...
If you see any other errors that are related to next-i18next please create a minimal reproducible example repository with reproducible steps that illustrates your error.
btw: your repository is still mixing stuff, like still using next-intl: https://github.com/nicitaacom/acc2-i18n/blob/development/app/%5Blocale%5D/layout.tsx#L3
and https://github.com/nicitaacom/acc2-i18n/blob/development/app/%5Blocale%5D/page.tsx#L2

this is not next-i18next... and also not plain i18next with app router... but your Next.js approach seems to be the app router approach... but you're still using next-i18next here: https://github.com/nicitaacom/acc2-i18n/blob/development/package.json#L20

So sorry, but please first learn the basics of Next.js (like the differences between pages approach and app approach), then decide which i18n framework you want to rely on... (this repo here is next-i18next (not even i18next core)) and not next-intl... next-intl is here: https://github.com/amannn/next-intl

**Closed by adrai** 2024-01-28 09:22 UTC

**Comment by nicitaacom** [comment] 2024-01-29 05:54
Why in this case I see error?

![image](https://github.com/i18next/next-i18next/assets/39565703/12d2d7b9-21ae-459b-b724-9e69ae7c38e2)

I use [this](https://locize.com/blog/next-app-dir-i18n/) guide and do exact same steps as in guide and see 

![image](https://github.com/i18next/next-i18next/assets/39565703/50773538-b4d7-466b-810b-5cc235657fc5)


I dan't understand naming of this `next-i18next` - if it for pages setup - name it like `pages-i18next` or `app-i18next`


I created this minimal example - https://github.com/nicitaacom/acc2-i18n
In this example I did `git clone` as you messaged

> Here a TypeScript example: https://github.com/i18next/next-13-app-dir-i18next-example-ts

as I see from naming its for app directory - so why do I get error in this example (I just did git clone)

As I see next steps you give me some guide or steps I need to do to implement internatiolization in my project with next 14 and app router setup
I'm preciate your answers
If you help me with this step - I will create guide on YouTube (cause I watched some guides and they doesn't work for me)
My guide may help other developers with intenatiolization

**Comment by adrai** [comment] 2024-01-29 06:18
I try to explain it the last time:

Your example: https://github.com/nicitaacom/acc2-i18n does NOT use i18next or at all... you are using next-intl (i.e. here: https://github.com/nicitaacom/acc2-i18n/blob/development/app/%5Blocale%5D/page.tsx#L2)

> I dan't understand naming of this next-i18next - if it for pages setup - name it like pages-i18next or app-i18next

Because next-i18next was created before Next.js introduced app router... so next-i18next is only for the older pages approach.

>> Here a TypeScript example: https://github.com/i18next/next-13-app-dir-i18next-example-ts

> as I see from naming its for app directory - so why do I get error in this example (I just did git clone)

I just tried it myself on 3 different machines, and it works... I don't see any errors.

**Comment by nicitaacom** [comment] 2024-01-30 07:40
> > as I see from naming its for app directory - so why do I get error in this example (I just did git clone)
> 
> I just tried it myself on 3 different machines, and it works... I don't see any errors.


I'm expect that I git clone this example and get no errors (I want to implement this example in my project)
Here is proof that I got an error

https://github.com/i18next/next-i18next/assets/39565703/d450d743-61e0-4596-9ec2-259fd68cc424

**Comment by nicitaacom** [comment] 2024-01-31 07:10
```
└─# cd ..       
git clone git@github.com:i18next/next-app-dir-i18next-example-ts.git
cd next-app-dir-i18next-example-ts
npm install
Cloning into 'next-app-dir-i18next-example-ts'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
cd: no such file or directory: next-app-dir-i18next-example-ts
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/kali/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/kali/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-01-31T07_09_36_136Z-debug-0.log
```



https://github.com/i18next/next-i18next/assets/39565703/48ccac6c-ee1e-48be-b3b3-19207e893096

**Comment by nicitaacom** [comment] 2024-02-01 05:47
![image](https://github.com/i18next/next-i18next/assets/39565703/ed343ac0-43d4-46cd-a8c8-71475994c963)

![image](https://github.com/i18next/next-i18next/assets/39565703/bd06b3a5-9bd9-4d02-9a83-42b3a7b94147)


:)




![temp](https://github.com/i18next/next-i18next/assets/39565703/bf14cb04-a5be-466c-93da-07955f6de755)



![image](https://github.com/i18next/next-i18next/assets/39565703/dc25f003-0412-402c-83ea-926ccc4a3c8c)


### Me

![poker face](https://github.com/i18next/next-i18next/assets/39565703/a1fc8861-1103-4444-8153-93edfe8f6110)



## Please help
I'm waiting that you send some instructions I need to do in this case
Or quick video that it work for you and then I do the same (run `pnpm build`)

**Comment by adrai** [comment] 2024-02-01 06:04
I'll try to explain this the last time.

https://github.com/i18next/next-app-dir-i18next-example-ts and https://github.com/nicitaacom/acc2-i18n are 2 repositories each one with its own package.json and each one being an individual Next.js project.
You can't have one inside the other....
So forget about your acc2-i18n folder for a moment...
Just open your terminal (not Visual Code) and then do this:

```sh
cd ~/Documents/GitHub
git clone https://github.com/i18next/next-app-dir-i18next-example-ts.git
cd next-app-dir-i18next-example-ts
npm install
```

After that try to compare that project with your acc2-i18n project...

Seems you're lacking the basics of how git and node.js and Next.js works on your file system...

Since it is not my responsibility to teach you these things and I don't have time for it (I have already invested too much time for you), I will not answer you anymore from now on.
Good luck.

**Comment by nicitaacom** [comment] 2024-02-02 07:29
> I will not answer you anymore from now on. Good luck.


Bro its issue in YOUR repository
And I did what YOU said
And its not my problem that after doing what you messaged I have errors

![image](https://github.com/i18next/next-i18next/assets/39565703/063c29d3-8667-481e-a8f8-76d1271b2faa)


And even after
```
cd ~/Documents/GitHub
git clone https://github.com/i18next/next-app-dir-i18next-example-ts.git
cd next-app-dir-i18next-example-ts
npm install
```

I have the same issue because *your* respositoty is NOT TypeScript version (as you see on screenshot)
I'm waiting update from you up to TypeScript version of `https://github.com/i18next/next-app-dir-i18next-example-ts.git` repository
because in name I see ts but in fact its not TypeScript version and if you run `pnpm build` it trow error

**Comment by adrai** [comment] 2024-02-02 07:44
Please try one last time... I just updated all dependencies to be sure everything is up-to-date:

```sh
cd ~/Documents/GitHub
git clone https://github.com/i18next/next-app-dir-i18next-example-ts.git
cd next-app-dir-i18next-example-ts
npm install
```

**Comment by nicitaacom** [comment] 2024-02-03 06:59
> If that still shows the errors in your editor, then please run `npm run lint` if that works, then your visual code setup might influence it...

I'm sure that vs code setup don't cause TypeError
```
Binding element 'lng' implicitly has an 'any' type.ts(7031)
(parameter) lng: any
```


https://github.com/i18next/next-i18next/assets/39565703/11190491-65b6-4b53-8368-eaedeecea1ad

**Comment by adrai** [comment] 2024-02-03 07:27
<img width="495" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/70f1d9fd-ad37-475b-9f32-8fd8d350ea7f">
I see only typescript...

btw: since TypeScript is a superset of Javascript the code always works... (npm run dev)...
Only lint has a problem....

**Comment by nicitaacom** [comment] 2024-02-04 07:49
Now `npm run lint` work and `pnpm build` throw no error
Thank you for fix

Waiting for es lint warning fix
`React Hook useEffect has a missing dependency: 'setCookie'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps`

**Comment by nicitaacom** [comment] 2024-02-04 07:51
Also I see this overflow issue

![image](https://github.com/i18next/next-i18next/assets/39565703/3b3116c7-437b-48c8-b003-ae499649aec9)

I'm waiting for fix for that as well

**Comment by adrai** [comment] 2024-02-04 07:59
it's not an error, but a warning... and it's like that on purpose...
The overflow is just styling with smaller screens

**Comment by nicitaacom** [comment] 2024-02-04 08:05
> it's not an error, but a warning... and it's like that on purpose... The overflow is just styling with smaller screens

Yes I mean warning
![image](https://github.com/i18next/next-i18next/assets/39565703/0d039b41-f7e7-4781-b06a-5787c07fd7df)

Should be no overflow x
Even for small screens should be no overflow x

I created PR - check it whenever you have time
https://github.com/i18next/next-app-dir-i18next-example-ts/pull/7

**Comment by nicitaacom** [comment] 2024-02-04 08:07
> and it's like that on purpose...

In this case I find it better to write comment why its on purpose

**Comment by adrai** [comment] 2024-02-04 08:10
You know, this is just an example: https://github.com/i18next/next-app-dir-i18next-example-ts
You can do in your code whatever you want...

**Comment by adrai** [comment] 2024-02-04 08:11
> Yes I mean warning
> ![image](https://private-user-images.githubusercontent.com/39565703/302086822-0d039b41-f7e7-4781-b06a-5787c07fd7df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzQ1NTEsIm5iZiI6MTcwNzAzNDI1MSwicGF0aCI6Ii8zOTU2NTcwMy8zMDIwODY4MjItMGQwMzliNDEtZjdlNy00NzgxLWIwNmEtNTc4N2MwN2ZkN2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA4MTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNGY1MzE5Y2JmYTQxNGZkYWExYmE5Mzc2Y2ZmYmUwN2I1NWExZDgyNGM3MWE5OWM3NWUzOGQ0MmU4MmI5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E6XM0BCLK4SUKxWEvV7jz0i8ojlPio4qbqBhzjsxPJ8)

https://github.com/i18next/next-app-dir-i18next-example-ts/commit/4da33605fbb4ae30830d64b3759ee6a7e15243e7
